#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

yarn format && yarn lint && yarn test

# Generate API.md then git add
yarn ts-node -P ./tsconfig.json ./scripts/swagger-generator.ts
git add ./API.md
